### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ratson**

### CODE REVIEW

**Comment by lindner** [comment]
Is anyone going to look at this?

**Comment by lindner** [comment]
@nolanlawson would you mind merging this and possible republishing?

**Comment by shadow81627** [comment]
Is this package maintained any more? It is annoying to have snyk error while checking dependencies due to an invalid semver. It would be nice to have this PR merged.

`es3ify` was using a deprecated version of `esprima-fb` which is resolved in version 2.0
https://github.com/sophiebits/es3ify/pull/8

**Comment by openscript** [comment]
This is superseded by #34. Hopefully the new package is soon released. Waiting for feedback from @nolanlawson.

**Pull request closed without merging**
