### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by openscript**
Most of the dependencies are quite outdated. After the upgrade the tests didn't work anymore, especially the on create callback of PouchDB does seem to be gone. I've also removed the `async` function and replaced it with promises.

The reason for the upgrade was a conflict:
`warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/node/.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity/node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic behavior, skipping.`

### CODE REVIEW

**Comment by openscript** [comment]
@nolanlawson @marten-de-vries It would be great if you can look into this within a week. Sorry for the messy commits with the yarn lock file.

**Comment by marten-de-vries** [comment]
@openscript Looks good to me. In the interest of also being able to merge a similar effort 5 years from now, I thought I'd increase the bus factor a bit by adding you as a collaborator on Github and NPM. I did the first, but it turns out I don't have access to the latter myself. Anyway, feel free to merge this into the main branch/release (when possible). :+1: 

@nolanlawson Could you add me (https://www.npmjs.com/~commandoline) and @openscript (https://www.npmjs.com/~openscript, I presume) as NPM collaborators for ``pouchdb-all-dbs``? Thanks!

**Comment by marten-de-vries** [comment]
I've just sent Nolan an email. He's moved on to other things, so it's not surprising he didn't see the pings so far. He did a very good job giving access to other contributors to other PouchDB libraries, but he authored so many it's not surprising that one was overlooked. Especially as ``pouchdb-all-dbs`` is as close to 'done' as its gets for a node project...

**Comment by openscript** [comment]
I also totally understand him.. sometimes just other things become more interesting. Let's hope that he sees the email.  😊

It would be great if Github and NPM had a feature for such situations. Like handing out write access when someone request it for a package or repo which was not maintained for a while. Or even privileges sharing between Github and NPM ..

**Comment by marten-de-vries** [comment]
@openscript We're in luck, Nolan responded already:

```bash
marten@procyon:~/git/pouchdb-all-dbs$ npm access ls-collaborators
{
  "nolanlawson": "read-write",
  "commandoline": "read-write",
  "openscript": "read-write"
}
```

Will you do the honours? (i.e. npm publish)

**Comment by openscript** [comment]
Awesome! :) Thank you @marten-de-vries for company! Just published 1.1.0. Hopefully I did everything right.. I didn't do this too often.

**Pull request merged**
